### ISSUE TITLE
module not loaded due to missing language file

### ISSUE THREAD

**Issue by cryptoreporter** [coinbase/coinbase-zencart#1]
Hi! So I followed the easy to read instructions and installed the files in my root ZenCart folder. I believe its located here...

Module Directory: /home/bitcoina/public_html/includes/modules/payment/

When I go into my ZenCart account and then to Modules>Payment, the Coinbase module is not there and I get an error at the top of the screen...

ERROR: module not loaded due to missing language file: /home/bitcoina/public_html/includes/languages/english/modules/payment/coinbasepp_callback.php

Am I doing anything wrong? Anything else I can try? Thanks!

(I have tried copying the "coinbasepp_callback.php" and putting it into the missing language file directory but it didnt help :) )

**Comment by aianus** [comment]
Did you check the unix permissions on the files you copied over and make sure they match up with the rest of your files? They might be unreadable by your web server process.

``` bash
ls -al
```

**Comment by cryptoreporter** [comment]
Thanks for the reply.

Permissions all look the same (644) as the files that are already in the zencart directory. While in my ZenCart admin under Modules>Payment it is telling me the ZenCart Module Directory is here: /home/bitcoina/public_html/includes/modules/payment/

Ive looked around my folders in cpanel and that looks like where all the zencart stuff is. Also on the Modules>Payment page in ZenCart admin its telling me (after putting the Coinbase/Zencart files in the above directory) the error...

ERROR: module not loaded due to missing language file: /home/bitcoina/public_html/includes/languages/english/modules/payment/coinbasepp_callback.php

There was/is no "coinbasepp_callback.php" in that directory. If I put a copy of it in there it essentially hides all my other payment modules in Modules>Payment. And it still doesnt show Coinbase as an option in Zencart admin.

**Comment by aianus** [comment]
The zip file is meant to be unzipped in your root zencart directory (/home/bitcoina/public_html). The folders are already in the zip file so it would automatically place the relevant files under includes/modules/payment/ and includes/languages/english.

I would remove any coinbase-related files in your zencart folder and just run `unzip master.zip` in /home/bitcoina/public_html and try again.

**Comment by cryptoreporter** [comment]
That did it!  Thanks!

**Comment by aianus** [comment]
Great, good luck with your store!
