### ISSUE TITLE
Installed, But Problems

### ISSUE THREAD

**Issue by cryptoreporter** [coinbase/coinbase-zencart#2]
Sorry to bother. Not sure if this is a ZenCart or Coinbase issue.

I have the module installed now and appears good. When I input my Client ID and Client Secret, all seems good. I click the update button to save. When I go back into the bitcoin module, it shows my ID & Secret, yet above it it says:

Merchant Account
No merchant account is connected.

I have filled out all merchant info with Coinbase. Name, address, phone, tax ID, etc. Not sure what to do now. Thanks for all the help!

**Comment by cryptoreporter** [comment]
Now, after a period of time, the inputed ID and secret have disappeared and I get this message:

Merchant Account
No merchant account connected; not ready to accept payments (click Edit to set up an account)

**Comment by cryptoreporter** [comment]
As a precaution I did a complete reinstall of my website, zencart and coinbase module. The Coinbase module does not work for me. After inputting my API info (key + secret) I get this message now...

"The redirect uri included is not valid. Please ensure that you are using a secure https connection as your redirect link."

Also, if I attempt to make a purchase on my site the checkout page goes to a blank secret, not a coinbase payment page.

The other bitcoin module available for zencart works without problem, but Ive been with Coinbase for a long time, familiar with it and wanted to keep my loyalty here with Coinbase.

Any help would be a appreciated! Thanks!

**Comment by leanstartpad** [comment]
Did you get it working?

I am trying to install on zenCart v1.5.5 and it is not going well.

Had to manually copy the files where they needed to be, but Admin tool didn't see it???

Is this module still supported?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
