### ISSUE TITLE
Open Redirect & CRLF Injection (on older versions of PHP) in Coinbase Zencart Plugin

### ISSUE THREAD

**Issue by Shinkurt** [coinbase/coinbase-zencart#5]
Bored, I sometimes go read old bits of code. I know libs aren't eligible for bounties and this is redirected from a hackerone report.

While checking out your php github repros, I noticed a very common mistake to send user supplied input to header() -- often leading to CRLF Injections on PHP versions <= 5.4.1 & according to the internet most of the sites running PHP are still are using them.

Whats more is I noticed a few assumptions all over the PHP code on what some global functions return.

### Examples
Take https://github.com/coinbase/coinbase-zencart/blob/master/coinbasepp_callback.php:

...
```
20: // Admin connecting OAuth account
  $hostPart = "http" . (($_SERVER['SERVER_PORT']==443) ? "s://" : "://") . $_SERVER['HTTP_HOST'];
  $pathParts = explode("?", $_SERVER['REQUEST_URI']);
  $url = $hostPart . $pathParts[0] . "?type=oauth&after=" . urlencode($_GET['after']);
  $oauth = new Coinbase_Oauth(MODULE_PAYMENT_COINBASE_OAUTH_CLIENTID, MODULE_PAYMENT_COINBASE_OAUTH_CLIENTSECRET, $url);
...
36: zen_redirect($hostPart . $_GET['after']);
```
Notice a few mistakes there, I'll first paste the zen_redirect() function hereas defined by ZenCart as:

```
function zen_redirect($url) {
      global $logger;

    // clean up URL before executing it
        while (strstr($url, '&&')) $url = str_replace('&&', '&', $url);
        while (strstr($url, '&amp;&amp;')) $url = str_replace('&amp;&amp;', '&amp;', $url);
        // header locates should not have the &amp; in the address it breaks things
        while (strstr($url, '&amp;')) $url = str_replace('&amp;', '&', $url);

        echo $url;

        exit;
      }
```
## First Bug: Sensitive Open Redirect
The first mistake is assuming $hostPart will be an absolute URL. printing $hostPart on my device is https://localhost and not https://localhost/ -- notice the forward slash.

So attacker can pass query parameters like ?after=@evil.com or even ?after=.evil.com and it will send https://localhost@evil.com or https://localhost.evil.com instead of https://localhost/@evil or .evil

That clearly results a sensitive open redirect in multiple areas throughout the code.

## Second Bug: CRLF on older PHP <= 5.4.1

Notice how the GET parameter after is never escaped before being sent to zen_redirect() , which by its nature just sends it to header() -- resulting in a clean CRLF Injection.

This can be confirmed by sending ?after=%0Dnew:header in Google Chrome/IE.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
