### ISSUE TITLE
Manipulation of variables leading to Unknown potentially dangerous issues

### ISSUE THREAD

**Issue by Shinkurt** [coinbase/coinbase-zencart#6]
### Summary

This vulnerability lays on your Coinbase-WPecommerce integration module's PHP library. It calls the native php function unset() - a function used to destroy variables sent to it. It does this multiple times with user control input which lets attacks manipulate sensitive variables in the site configurations or the module it self

The affected file is:

https://github.com/coinbase/coinbase-wpecommerce/blob/b64665f9b4b68bff4539dd855a5bd7d8502d9164/wp-content/plugins/wp-e-commerce/wpsc-merchants/coinbase.merchant.php

### Explaination
As you can see at the following lines a user input is being sent to unset(),

187: unset($_REQUEST['order']);
188: unset($_GET['order']);
because of that rare opportunity we can destroy any variable and cause a potential flow control bypass.

so by rewriting/destroying (unsetting) variables like $callback_secret, $apiSecret or similar one can send arbitrary empty NULL variables (or not) and cause a check bypass.

This mostly would be practical in a victim that implemented that code and put his sensitive variables like $callback_secret, $apiSecret... or other sensitive wallets (that maybe balance,configs...) we can then unset() these variables and pass incorrect parameters and cause a check bypass leading to various kind of attack scenarios.

Thanks,

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
